default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Internal track"
  lane :internal do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: "internal")
  end

  desc "Promote Internal to Production"
  lane :promote_to_prod do
    upload_to_play_store(track: "production", from_track: "internal")
  end
end
